global:
  scrape_interval: 15s

scrape_configs:
  # 1. Monitoring dyal l-Infrastructure (CPU, RAM, etc.)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # 2. Monitoring dyal l-Uptime/SLA (Wach l-site khdam)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Kantisnnaw natija dyal 200 OK
    static_configs:
      - targets:
        - https://www.google.com
        - http://prometheus:9090
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

